
esphome:
  name: "yuzha-liquidlevel1"
  friendly_name: "Yuzha liquidlevel1 Sensor"
  platformio_options: 
    board_build.flash_mode: dio
  project:
    name: yuzha.liquidlevel1
    version: "1.0"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: "yuzha2024"

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin: 4
    name: liquidlevel-onepoint
    filters:
      - invert:
      - delayed_on: 100ms
      - delayed_off: 100ms 